CREATE TABLE IF NOT EXISTS collections (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  model_name VARCHAR(255) NOT NULL,
  amk_code VARCHAR(100) DEFAULT '',
  hero_image VARCHAR(255) DEFAULT NULL,
  main_product_id INT UNSIGNED DEFAULT NULL,
  selected_products JSON DEFAULT NULL,
  sort_order INT DEFAULT 0,
  status ENUM('active', 'inactive') DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
